
[[models]]
path = "../../../interface/"
files = [
    "eventsourcing.smithy",
    "process_manager.smithy",
    "aggregate.smithy"
]

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@wasmcloud-core-interface-v0.2.0/core/wasmcloud-core.smithy"

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@wasmcloud-model-interface-v0.2.0/core/wasmcloud-model.smithy"

##
## HTML documentation output
##
[html]

# (optional) template dir to scan (overrides compiled-in templates)
#templates = "docgen/templates"
# Top-level output directory for html generated files
output_dir = "html"

# Additional parameters for html generation
[html.parameters]

# name of template for page generation (default: 'namespace_doc')
#doc_template = "namespace_doc"

# whether to use minified tailwind.css (default false)
minified = true


##
## Rust language output
##
[rust]

# top-level output directory for rust files.
output_dir = "./src"
#templates = "codegen/"

[rust.parameters]

# File-specific settings contain the following settings
# [[rust.files]]
# path - (required) path for generated output file, relative to output_dir above
# hbs - handlebars template name (without .hbs extension)
# Only applicable if file is generated by a handlebars template
# create_only - whether file should be generated only with --create (default false)
# namespace - limit generated shapes to shapes in this namespace
# * - any other fields are per-file parameters passed to codegen and renderer

# Additional namespaces may be added to this library crate by adding
# a rust source file below for each namespace,
# and importing each of them into src/lib.rs

[[rust.files]]
path = "./eventsourcing.rs"
namespace = "com.cosmonic.eventsourcing"
