[[models]]
path = "../interface/"
files = [
    "eventsourcing.smithy",
    "aggregate.smithy"
]

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@wasmcloud-core-interface-v0.2.0/core/wasmcloud-core.smithy"

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@wasmcloud-model-interface-v0.2.0/core/wasmcloud-model.smithy"


[html]
output_dir = "html"

[html.parameters]
minified = true

[rust]
output_dir = "./src"

[rust.parameters]


[[rust.files]]
path = "./eventsourcing.rs"
namespace = "com.cosmonic.eventsourcing"