[package]
name = "concordance-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
rdf = "0.1.4"
handlebars = "4.3.3"
Inflector = "0.11.4"
rust-embed = {version = "6.4.0", features = ["debug-embed"] }
serde = {version = "1.0.144", features = ["derive"] }
serde_json = "1.0.64"
