[[models]]
path = "../../interface/"
files = [
    "eventsourcing.smithy",
    "process_manager.smithy",
    "aggregate.smithy"
]

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@wasmcloud-core-interface-v0.2.0/core/wasmcloud-core.smithy"

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@wasmcloud-model-interface-v0.2.0/core/wasmcloud-model.smithy"



##
## Rust language output
##
[rust]

# top-level output directory for rust files.
output_dir = "./src"
#templates = "codegen/"

[rust.parameters]


[[rust.files]]
path = "./eventsourcing.rs"
namespace = "com.cosmonic.eventsourcing"